site_name: Archivey
nav:
  - Home: index.md
  - User guide: user_guide.md
  - Developer guide: developer_guide.md
  - API reference: api.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            heading_level: 3
            show_source: false
  - autorefs
theme:
  name: readthedocs
  navigation_depth: 3
