site_name: Archivey
nav:
  - Home: index.md
  - User guide: user_guide.md
  - Developer guide: developer_guide.md
  - API reference: api.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
  - autorefs
