from typing import Any

class Decompress:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def decompress(self, chunk: bytes) -> bytes: ...
    def flush(self) -> bytes: ...
    @property
    def eof(self) -> bool: ...
